[package]
name = "advent-of-code-2019-day-2"
version = "0.1.0"
authors = ["Tim Hoiberg <tim.hoiberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
